### ISSUE TITLE
How to measure mobile device training.

### ISSUE THREAD

**Issue by codestar12** [boone891214/MEST#3]
Hello, is there a portion of the code that was used for measuring mobile device training? I can’t seem to find it.

**Comment by Bolloo** [comment]
> Hello, is there a portion of the code that was used for measuring mobile device training? I can’t seem to find it.
Hi! 
Thank you for being interested in our work. We don’t have an end-to-end training code for mobile devices. The acceleration rate is measured based on layer-wise accumulation of the forward and backward time. We adopt the compiler optimizations (from PatDNN) to support sparse computation. Unfortunately, due to the intellectual property issue, that part of the code cannot be public. For more information about the compiler optimizations can be found in [PatDNN](https://dl.acm.org/doi/pdf/10.1145/3373376.3378534), [GRIM](https://arxiv.org/pdf/2108.11033.pdf), and [CoCoPIE](https://cacm.acm.org/magazines/2021/6/252819-cocopie/fulltext).
